//! The sole structural compiler for the checked-in Draft-07 definition.
//! It runs during the build; generated runtime tables contain no compiler.
use std::collections::{BTreeMap, BTreeSet};

use crate::json::{Document, Kind, Limits, Value};

pub struct Compilation {
    pub rust: String,
    pub inventory: String,
    pub discriminators: BTreeMap<String, Vec<String>>,
    /// The terminal table, in the contract's order: every result subtype,
    /// whether it is an error, and the exit code a process that ended with it
    /// leaves.
    pub terminal_outcomes: Vec<(String, bool, u8)>,
    pub success_subtype: String,
    pub error_subtypes: Vec<String>,
}

#[derive(Default)]
struct Compiler {
    nodes: Vec<CompiledNode>,
    paths: BTreeMap<String, usize>,
    references: Vec<(usize, usize, String)>,
    keywords: BTreeMap<String, usize>,
    object_schemas: usize,
    false_schemas: usize,
    true_schemas: usize,
}

#[derive(Default)]
struct CompiledNode {
    path: String,
    rules: Vec<String>,
    same_instance: Vec<usize>,
}

fn error(path: &str, cause: impl std::fmt::Display) -> String {
    format!("schema definition {path}: {cause}")
}
fn escaped(name: &str) -> String {
    name.replace('~', "~0").replace('/', "~1")
}
fn child_path(path: &str, name: &str) -> String {
    format!("{path}/{}", escaped(name))
}
fn string<'a>(value: Value<'a>, path: &str) -> Result<&'a str, String> {
    value
        .as_str()
        .ok_or_else(|| error(path, "expected a string"))
}
fn strings(value: Value<'_>, path: &str) -> Result<Vec<String>, String> {
    let values = value
        .elements()
        .ok_or_else(|| error(path, "expected an array of unique strings"))?;
    let mut result = Vec::new();
    let mut seen = BTreeSet::new();
    for value in values {
        let text = string(value, path)?.to_string();
        if !seen.insert(text.clone()) {
            return Err(error(path, "duplicate string"));
        }
        result.push(text);
    }
    Ok(result)
}

pub fn compile(bytes: &[u8]) -> Result<Compilation, String> {
    let document = Document::decode(
        bytes,
        Limits {
            bytes: bytes.len(),
            nodes: bytes.len(),
            depth: 512,
        },
    )
    .map_err(|cause| error("", format!("exact JSON decoding failed: {cause:?}")))?;
    let root = document.root();
    if root.get("$schema").and_then(Value::as_str)
        != Some("http://json-schema.org/draft-07/schema#")
    {
        return Err(error("/$schema", "expected the owned Draft-07 dialect"));
    }
    if root.get("$id").and_then(Value::as_str) != Some("urn:agent-service:stream-contract:1") {
        return Err(error("/$id", "unexpected owned schema identity"));
    }
    let mut compiler = Compiler::default();
    compiler.node(root, "")?;
    for (node, rule, target) in &compiler.references {
        let id = *compiler.paths.get(target).ok_or_else(|| {
            error(
                &compiler.nodes[*node].path,
                format!("unresolved local reference #{target}"),
            )
        })?;
        compiler.nodes[*node].rules[*rule] = format!("Rule::Ref({id})");
        compiler.nodes[*node].same_instance.push(id);
    }
    compiler.check_cycles()?;

    let mut rust = String::from("// Generated by protocol/engine/schema_compiler.rs.\n\n");
    rust.push_str("pub(crate) static NODES: &[SchemaNode] = &[\n");
    for node in &compiler.nodes {
        rust.push_str(&format!(
            "SchemaNode {{ path: {:?}, rules: &[{}] }},\n",
            node.path,
            node.rules.join(",")
        ));
    }
    rust.push_str("];\n\n#[derive(Clone, Copy, Debug)]\npub enum SchemaEntry { Record,\n");
    let definitions = root
        .get("definitions")
        .ok_or_else(|| error("/definitions", "missing owned definitions"))?;
    let mut entries = vec![("Record".into(), 0usize)];
    let mut entry_names = BTreeSet::from(["Record".to_string()]);
    for (name, _) in definitions
        .members()
        .ok_or_else(|| error("/definitions", "expected an object"))?
    {
        let ident = identifier(name)?;
        if ident == "Self" || !entry_names.insert(ident.clone()) {
            return Err(error(
                &child_path("/definitions", name),
                format!("generated entry identifier {ident} is reserved or duplicated"),
            ));
        }
        rust.push_str(&format!("{ident},\n"));
        entries.push((
            ident,
            compiler.paths[&format!("/definitions/{}", escaped(name))],
        ));
    }
    rust.push_str("}\nimpl SchemaEntry { fn node(self) -> usize { match self {\n");
    for (name, id) in &entries {
        rust.push_str(&format!("Self::{name} => {id},\n"));
    }
    rust.push_str("}}}\n");

    let top = root
        .get("oneOf")
        .ok_or_else(|| error("/oneOf", "missing event alternatives"))?;
    let system = top
        .elements()
        .and_then(|mut elements| {
            elements.find(|variant| {
                variant
                    .get("properties")
                    .and_then(|properties| properties.get("type"))
                    .and_then(|property| property.get("const"))
                    .and_then(Value::as_str)
                    == Some("system")
            })
        })
        .and_then(|first| first.get("oneOf"))
        .ok_or_else(|| error("/oneOf", "missing system alternatives"))?;
    let partial = definitions
        .get("streamEvent")
        .and_then(|value| value.get("oneOf"))
        .ok_or_else(|| error("/definitions/streamEvent", "missing partial alternatives"))?;
    let discriminators = [
        ("EventKind", discriminators(top, "type")?),
        ("SystemKind", discriminators(system, "subtype")?),
        ("PartialKind", discriminators(partial, "type")?),
    ]
    .into_iter()
    .map(|(name, values)| (name.to_string(), values))
    .collect();
    let terminal_outcomes = terminal_outcomes(definitions)?;
    let mut successes = terminal_outcomes
        .iter()
        .filter(|(_, is_error, _)| !is_error);
    let success_subtype = match (successes.next(), successes.next()) {
        (Some((name, _, _)), None) => name.clone(),
        _ => {
            return Err(error(
                "/definitions/terminalOutcome",
                "expected exactly one terminal outcome that is not an error",
            ))
        }
    };
    let error_subtypes = terminal_outcomes
        .iter()
        .filter(|(_, is_error, _)| *is_error)
        .map(|(name, _, _)| name.clone())
        .collect::<Vec<_>>();
    if error_subtypes.is_empty() {
        return Err(error(
            "/definitions/terminalOutcome",
            "expected at least one terminal outcome that is an error",
        ));
    }
    let inventory = serde_json::to_string_pretty(&serde_json::json!({
        "dialect": "http://json-schema.org/draft-07/schema#",
        "object_schemas": compiler.object_schemas,
        "false_schemas": compiler.false_schemas,
        "true_schemas": compiler.true_schemas,
        "keywords": compiler.keywords,
        "references": compiler.references.iter().map(|(node, _, target)| serde_json::json!({"source": compiler.nodes[*node].path, "target": target})).collect::<Vec<_>>(),
        "nodes": compiler.nodes.iter().map(|node| serde_json::json!({"path": node.path, "rules": node.rules, "same_instance": node.same_instance})).collect::<Vec<_>>(),
        "entries": entries,
    })).map_err(|cause| cause.to_string())?;
    Ok(Compilation {
        rust,
        inventory,
        discriminators,
        terminal_outcomes,
        success_subtype,
        error_subtypes,
    })
}

/// The terminal table: one alternative per result subtype, each stating the
/// subtype, whether it is an error, and the exit code a process that ended
/// with it leaves, all as exact constants. The subtype and error flag are
/// required, so the same alternatives validate a terminal record's pairing;
/// the exit code is what the table adds for a reader of the process.
fn terminal_outcomes(definitions: Value<'_>) -> Result<Vec<(String, bool, u8)>, String> {
    let path = "/definitions/terminalOutcome";
    let definition = definitions
        .get("terminalOutcome")
        .ok_or_else(|| error(path, "missing the terminal table"))?;
    if definition.members().map(|members| members.count()) != Some(1) {
        return Err(error(
            path,
            "expected exactly one oneOf of terminal outcomes",
        ));
    }
    let rows = definition
        .get("oneOf")
        .and_then(Value::elements)
        .ok_or_else(|| error(path, "expected a oneOf of terminal outcomes"))?;
    let mut outcomes = Vec::new();
    let mut names = BTreeSet::new();
    for (index, row) in rows.enumerate() {
        let path = format!("{path}/oneOf/{index}");
        let keys = row
            .members()
            .map(|members| members.map(|(key, _)| key).collect::<BTreeSet<_>>());
        if keys != Some(BTreeSet::from(["properties", "required"])) {
            return Err(error(&path, "expected exactly properties and required"));
        }
        let required = row
            .get("required")
            .map(|value| strings(value, &path))
            .transpose()?
            .map(|names| names.into_iter().collect::<BTreeSet<_>>());
        if required
            != Some(BTreeSet::from([
                "subtype".to_string(),
                "is_error".to_string(),
            ]))
        {
            return Err(error(&path, "expected subtype and is_error to be required"));
        }
        let properties = row.get("properties").expect("checked above");
        let fields = properties
            .members()
            .map(|members| members.map(|(key, _)| key).collect::<BTreeSet<_>>());
        if fields != Some(BTreeSet::from(["subtype", "is_error", "exit_code"])) {
            return Err(error(
                &path,
                "expected exactly subtype, is_error and exit_code",
            ));
        }
        let constant = |field: &str| {
            let value = properties.get(field).expect("checked above");
            if value.members().map(|members| members.count()) != Some(1) {
                return Err(error(&path, format!("{field} must be exactly one const")));
            }
            value
                .get("const")
                .ok_or_else(|| error(&path, format!("{field} must be exactly one const")))
        };
        let name = constant("subtype")?
            .as_str()
            .filter(|name| !name.is_empty())
            .ok_or_else(|| error(&path, "subtype must be a nonempty name"))?
            .to_string();
        let is_error = constant("is_error")?
            .as_bool()
            .ok_or_else(|| error(&path, "is_error must be a boolean"))?;
        let exit_code = constant("exit_code")?
            .as_number()
            .and_then(|number| number.as_unsigned(255).ok())
            .ok_or_else(|| error(&path, "exit_code must be an integer from 0 to 255"))?;
        if !names.insert(name.clone()) {
            return Err(error(&path, "terminal names must be distinct"));
        }
        outcomes.push((name, is_error, exit_code as u8));
    }
    Ok(outcomes)
}

fn identifier(name: &str) -> Result<String, String> {
    if name.is_empty()
        || !name.bytes().all(|byte| byte.is_ascii_alphanumeric())
        || !name.as_bytes()[0].is_ascii_alphabetic()
    {
        return Err(error(name, "unsupported generated entry identifier"));
    }
    Ok(format!("{}{}", name[..1].to_ascii_uppercase(), &name[1..]))
}

fn discriminators(value: Value<'_>, key: &str) -> Result<Vec<String>, String> {
    let mut result = Vec::new();
    let mut seen = BTreeSet::new();
    for variant in value
        .elements()
        .ok_or_else(|| error(key, "missing variant array"))?
    {
        let name = variant
            .get("properties")
            .and_then(|properties| properties.get(key))
            .and_then(|property| property.get("const"))
            .and_then(Value::as_str)
            .ok_or_else(|| error(key, "each variant must declare a string discriminator"))?;
        if !seen.insert(name.to_string()) {
            return Err(error(key, "duplicate variant discriminator"));
        }
        if name == "self"
            || name
                .split('_')
                .any(|part| part.is_empty() || !part.bytes().all(|byte| byte.is_ascii_lowercase()))
        {
            return Err(error(
                key,
                format!("unsupported generated discriminator identifier {name:?}"),
            ));
        }
        result.push(name.into());
    }
    Ok(result)
}

impl Compiler {
    fn node(&mut self, value: Value<'_>, path: &str) -> Result<usize, String> {
        if self.paths.contains_key(path) {
            return Err(error(path, "duplicate schema path"));
        }
        let id = self.nodes.len();
        self.paths.insert(path.into(), id);
        self.nodes.push(CompiledNode {
            path: path.into(),
            ..Default::default()
        });
        if let Some(boolean) = value.as_bool() {
            if boolean {
                self.true_schemas += 1;
            } else {
                self.false_schemas += 1;
                self.nodes[id].rules.push("Rule::False".into());
            }
            return Ok(id);
        }
        let members: Vec<_> = value
            .members()
            .ok_or_else(|| error(path, "a schema must be an object or boolean"))?
            .collect();
        self.object_schemas += 1;
        const KNOWN: &[&str] = &[
            "$schema",
            "$id",
            "definitions",
            "$ref",
            "type",
            "properties",
            "required",
            "additionalProperties",
            "const",
            "enum",
            "minimum",
            "maximum",
            "minLength",
            "maxLength",
            "pattern",
            "items",
            "minItems",
            "maxItems",
            "uniqueItems",
            "oneOf",
            "anyOf",
            "allOf",
            "if",
            "then",
        ];
        for (keyword, _) in &members {
            if !KNOWN.contains(keyword) {
                return Err(error(
                    &child_path(path, keyword),
                    "unsupported schema keyword",
                ));
            }
            *self.keywords.entry((*keyword).into()).or_default() += 1;
        }
        if let Some(dialect) = value.get("$schema") {
            if string(dialect, path)? != "http://json-schema.org/draft-07/schema#" {
                return Err(error(path, "unsupported schema dialect"));
            }
        }
        if let Some(identity) = value.get("$id") {
            if !path.is_empty() || string(identity, path)? != "urn:agent-service:stream-contract:1"
            {
                return Err(error(path, "unsupported nested schema resource identity"));
            }
        }
        if let Some(definitions) = value.get("definitions") {
            if !path.is_empty() {
                return Err(error(
                    path,
                    "nested definitions are not a supported owned schema form",
                ));
            }
            for (name, child) in definitions
                .members()
                .ok_or_else(|| error(path, "definitions must be an object"))?
            {
                self.node(child, &child_path(&child_path(path, "definitions"), name))?;
            }
        }
        if let Some(reference) = value.get("$ref") {
            if members
                .iter()
                .any(|(name, _)| !matches!(*name, "$ref" | "$schema"))
            {
                return Err(error(
                    path,
                    "Draft-07 reference assertion siblings are unsupported",
                ));
            }
            let reference = string(reference, path)?;
            let target = reference
                .strip_prefix('#')
                .ok_or_else(|| error(path, "only local definition references are supported"))?;
            let name = target
                .strip_prefix("/definitions/")
                .ok_or_else(|| error(path, "only local definition references are supported"))?;
            if name.is_empty() || name.contains('/') {
                return Err(error(path, "unsupported definition pointer"));
            }
            // Require canonical pointer escapes. A prefix-only resolver would
            // misinterpret literal '~' and '/' in definition member names.
            let mut decoded = String::new();
            let mut chars = name.chars();
            while let Some(character) = chars.next() {
                if character == '~' {
                    decoded.push(match chars.next() {
                        Some('0') => '~',
                        Some('1') => '/',
                        _ => return Err(error(path, "invalid JSON Pointer escape")),
                    });
                } else {
                    decoded.push(character);
                }
            }
            if escaped(&decoded) != name {
                return Err(error(path, "noncanonical definition pointer"));
            }
            self.references
                .push((id, self.nodes[id].rules.len(), target.into()));
            self.nodes[id].rules.push(String::new());
            return Ok(id);
        }
        if let Some(kind) = value.get("type") {
            let kinds = if let Some(kind) = kind.as_str() {
                vec![kind.into()]
            } else {
                strings(kind, path)?
            };
            if kinds.is_empty() {
                return Err(error(path, "type union must not be empty"));
            }
            let mut mask = 0u8;
            for kind in kinds {
                mask |= match kind.as_str() {
                    "null" => 1,
                    "boolean" => 2,
                    "number" => 4,
                    "integer" => 8,
                    "string" => 16,
                    "array" => 32,
                    "object" => 64,
                    _ => return Err(error(path, "unsupported JSON type")),
                };
            }
            self.nodes[id].rules.push(format!("Rule::Type({mask})"));
        }
        if let Some(literal) = value.get("const") {
            self.nodes[id]
                .rules
                .push(format!("Rule::Const({})", Self::literal(literal, path)?));
        }
        if let Some(literals) = value.get("enum") {
            let literals: Vec<_> = literals
                .elements()
                .ok_or_else(|| error(path, "enum must be an array"))?
                .collect();
            if literals.is_empty() {
                return Err(error(path, "enum must not be empty"));
            }
            let mut compiled = Vec::new();
            for (index, &literal) in literals.iter().enumerate() {
                if literals[..index].contains(&literal) {
                    return Err(error(path, "enum contains a duplicate exact value"));
                }
                compiled.push(Self::literal(literal, path)?);
            }
            self.nodes[id]
                .rules
                .push(format!("Rule::Enum(&[{}])", compiled.join(",")));
        }
        for (keyword, rule) in [("minimum", "Minimum"), ("maximum", "Maximum")] {
            if let Some(bound) = value.get(keyword) {
                let token = bound
                    .as_number()
                    .ok_or_else(|| error(path, "numeric bound must be a JSON number"))?
                    .token();
                self.nodes[id]
                    .rules
                    .push(format!("Rule::{rule}({token:?})"));
            }
        }
        for (keyword, rule) in [("minLength", "MinLength"), ("maxLength", "MaxLength")] {
            if let Some(bound) = value.get(keyword) {
                self.nodes[id]
                    .rules
                    .push(format!("Rule::{rule}({})", Self::count(bound, path)?));
            }
        }
        if let Some(pattern) = value.get("pattern") {
            let pattern = match string(pattern, path)? {
                "^[a-f0-9]{64}$" => "LowerHex64",
                "[^\\u0009-\\u000D\\u0020\\u00A0\\u1680\\u2000-\\u200A\\u2028\\u2029\\u202F\\u205F\\u3000\\uFEFF]" => "ContainsNonblankScalar",
                _ => return Err(error(&child_path(path, "pattern"), "unsupported pattern")),
            };
            self.nodes[id]
                .rules
                .push(format!("Rule::Pattern(Pattern::{pattern})"));
        }
        if ["properties", "required", "additionalProperties"]
            .iter()
            .any(|name| value.get(name).is_some())
        {
            let mut properties = Vec::new();
            if let Some(declared) = value.get("properties") {
                for (key, child) in declared
                    .members()
                    .ok_or_else(|| error(path, "properties must be an object"))?
                {
                    let child_id =
                        self.node(child, &child_path(&child_path(path, "properties"), key))?;
                    properties.push(format!("({key:?},{child_id})"));
                }
            }
            let required = value
                .get("required")
                .map(|required| strings(required, path))
                .transpose()?
                .unwrap_or_default();
            let additional = if let Some(additional) = value.get("additionalProperties") {
                format!(
                    "Additional::Schema({})",
                    self.node(additional, &child_path(path, "additionalProperties"))?
                )
            } else {
                "Additional::Allow".into()
            };
            self.nodes[id].rules.push(format!("Rule::Object {{ properties: &[{}], required: &{required:?}, additional: {additional} }}", properties.join(",")));
        }
        if ["items", "minItems", "maxItems", "uniqueItems"]
            .iter()
            .any(|name| value.get(name).is_some())
        {
            let items = value
                .get("items")
                .map(|items| self.node(items, &child_path(path, "items")))
                .transpose()?;
            let min = value
                .get("minItems")
                .map(|value| Self::count(value, path))
                .transpose()?;
            let max = value
                .get("maxItems")
                .map(|value| Self::count(value, path))
                .transpose()?;
            let unique = match value.get("uniqueItems") {
                None => false,
                Some(value) => value
                    .as_bool()
                    .ok_or_else(|| error(path, "uniqueItems must be a boolean"))?,
            };
            self.nodes[id].rules.push(format!(
                "Rule::Array {{ items: {items:?}, min: {min:?}, max: {max:?}, unique: {unique} }}"
            ));
        }
        for (keyword, rule) in [("allOf", "AllOf"), ("anyOf", "AnyOf"), ("oneOf", "OneOf")] {
            if let Some(branches) = value.get(keyword) {
                let mut children = Vec::new();
                for (index, child) in branches
                    .elements()
                    .ok_or_else(|| error(path, "combinator must be an array"))?
                    .enumerate()
                {
                    children.push(self.node(child, &format!("{}/{keyword}/{index}", path))?);
                }
                if children.is_empty() {
                    return Err(error(path, "combinator must not be empty"));
                }
                self.nodes[id].same_instance.extend(&children);
                self.nodes[id]
                    .rules
                    .push(format!("Rule::{rule}(&{children:?})"));
            }
        }
        match (value.get("if"), value.get("then")) {
            (None, None) => {}
            (Some(condition), Some(consequence)) => {
                let condition = self.node(condition, &child_path(path, "if"))?;
                let consequence = self.node(consequence, &child_path(path, "then"))?;
                self.nodes[id]
                    .same_instance
                    .extend([condition, consequence]);
                self.nodes[id].rules.push(format!(
                    "Rule::IfThen {{ condition: {condition}, consequence: {consequence} }}"
                ));
            }
            _ => return Err(error(path, "owned conditional requires both if and then")),
        }
        Ok(id)
    }

    fn count(value: Value<'_>, path: &str) -> Result<usize, String> {
        let number = value
            .as_number()
            .ok_or_else(|| error(path, "count must be numeric"))?;
        let count = number.as_unsigned(usize::MAX as u64).map_err(|cause| {
            error(
                path,
                format!("count exceeds the schema table index domain: {cause:?}"),
            )
        })?;
        Ok(count as usize)
    }

    fn literal(value: Value<'_>, path: &str) -> Result<String, String> {
        match value.kind() {
            Kind::Null => Ok("Literal::Null".into()),
            Kind::Boolean => Ok(format!("Literal::Bool({})", value.as_bool().unwrap())),
            Kind::Number => Ok(format!(
                "Literal::Number({:?})",
                value.as_number().unwrap().token()
            )),
            Kind::String => Ok(format!("Literal::String({:?})", value.as_str().unwrap())),
            Kind::Array | Kind::Object => Err(error(
                path,
                "composite definition literals are not yet a supported compiler capability",
            )),
        }
    }

    fn check_cycles(&self) -> Result<(), String> {
        let mut colors = vec![0u8; self.nodes.len()];
        for start in 0..self.nodes.len() {
            let mut pending = vec![(start, false)];
            while let Some((node, leaving)) = pending.pop() {
                if leaving {
                    colors[node] = 2;
                    continue;
                }
                match colors[node] {
                    2 => continue,
                    1 => {
                        return Err(error(
                            &self.nodes[node].path,
                            "schema recursion does not descend into the JSON value",
                        ))
                    }
                    _ => {}
                }
                colors[node] = 1;
                pending.push((node, true));
                pending.extend(
                    self.nodes[node]
                        .same_instance
                        .iter()
                        .rev()
                        .map(|&child| (child, false)),
                );
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    const SOURCE: &[u8] = include_bytes!("../stream-contract-v1.json");

    #[test]
    fn owned_vocabulary_inventory_is_complete() {
        let compiled = compile(SOURCE).unwrap();
        let inventory: serde_json::Value = serde_json::from_str(&compiled.inventory).unwrap();
        assert_eq!(inventory["object_schemas"], 373);
        assert_eq!(inventory["false_schemas"], 53);
        assert_eq!(inventory["keywords"].as_object().unwrap().len(), 24);
        assert_eq!(inventory["references"].as_array().unwrap().len(), 18);
        assert!(!compiled.rust.is_empty());
        assert_eq!(compiled.discriminators["EventKind"].len(), 5);
        assert_eq!(compiled.success_subtype, crate::SUCCESS_SUBTYPE);
        assert_eq!(compiled.error_subtypes, crate::ERROR_SUBTYPES);
        assert_eq!(
            compiled.terminal_outcomes.len(),
            crate::TERMINAL_OUTCOMES.len()
        );
        for ((subtype, is_error, exit_code), generated) in compiled
            .terminal_outcomes
            .iter()
            .zip(crate::TERMINAL_OUTCOMES)
        {
            assert_eq!(
                (subtype.as_str(), *is_error, *exit_code),
                (generated.subtype, generated.is_error, generated.exit_code)
            );
        }
    }

    fn outcome(subtype: &str, is_error: bool, exit_code: serde_json::Value) -> serde_json::Value {
        serde_json::json!({
            "properties": {
                "subtype": {"const": subtype},
                "is_error": {"const": is_error},
                "exit_code": {"const": exit_code},
            },
            "required": ["subtype", "is_error"],
        })
    }

    #[test]
    fn terminal_table_comes_from_the_definition_and_refuses_ambiguous_identity() {
        let source: serde_json::Value = serde_json::from_slice(SOURCE).unwrap();
        let mut changed = source.clone();
        changed["definitions"]["terminalOutcome"]["oneOf"] = serde_json::json!([
            outcome("completed", false, serde_json::json!(0)),
            outcome("refused", true, serde_json::json!(9)),
        ]);
        let compiled = compile(&serde_json::to_vec(&changed).unwrap()).unwrap();
        assert_eq!(compiled.success_subtype, "completed");
        assert_eq!(compiled.error_subtypes, ["refused"]);
        assert_eq!(
            compiled.terminal_outcomes,
            [
                ("completed".to_string(), false, 0),
                ("refused".to_string(), true, 9)
            ]
        );
        let ok = |name: &str| outcome(name, false, serde_json::json!(0));
        let failed = |name: &str, code: serde_json::Value| outcome(name, true, code);
        for rows in [
            // no outcome that is not an error, or two of them
            serde_json::json!([failed("refused", serde_json::json!(9))]),
            serde_json::json!([ok("a"), ok("b"), failed("c", serde_json::json!(1))]),
            // no error outcome
            serde_json::json!([ok("completed")]),
            // one name twice, or no name
            serde_json::json!([ok("completed"), failed("completed", serde_json::json!(1))]),
            serde_json::json!([ok(""), failed("refused", serde_json::json!(1))]),
            // an exit code no process can leave
            serde_json::json!([ok("completed"), failed("refused", serde_json::json!(256))]),
            serde_json::json!([ok("completed"), failed("refused", serde_json::json!(-1))]),
            serde_json::json!([ok("completed"), failed("refused", serde_json::json!("1"))]),
        ] {
            changed = source.clone();
            changed["definitions"]["terminalOutcome"]["oneOf"] = rows;
            assert!(compile(&serde_json::to_vec(&changed).unwrap()).is_err());
        }
        // An outcome states exactly its subtype, error flag and exit code, and
        // requires the two a terminal record carries.
        let mut unstated = ok("completed");
        unstated["properties"]
            .as_object_mut()
            .unwrap()
            .remove("exit_code");
        let mut extra = ok("completed");
        extra["properties"]["reason"] = serde_json::json!({"const": "x"});
        let mut unrequired = ok("completed");
        unrequired["required"] = serde_json::json!(["subtype"]);
        let mut open = ok("completed");
        open["properties"]["exit_code"] = serde_json::json!({"type": "integer"});
        for row in [unstated, extra, unrequired, open] {
            changed = source.clone();
            changed["definitions"]["terminalOutcome"]["oneOf"] =
                serde_json::json!([row, failed("refused", serde_json::json!(1))]);
            assert!(compile(&serde_json::to_vec(&changed).unwrap()).is_err());
        }
    }

    #[test]
    fn unsupported_or_incoherent_definitions_fail_before_runtime() {
        let source: serde_json::Value = serde_json::from_slice(SOURCE).unwrap();
        for (name, field, value, expected) in [
            (
                "goalCheckpointEvidenceBytes",
                "unknownAssertion",
                serde_json::json!(true),
                "unsupported schema keyword",
            ),
            (
                "goalCheckpointEvidenceBytes",
                "pattern",
                serde_json::json!(".*"),
                "unsupported pattern",
            ),
            (
                "goalCheckpointEvidenceBytes",
                "minimum",
                serde_json::json!("0"),
                "numeric bound must",
            ),
        ] {
            let mut changed = source.clone();
            changed["definitions"][name][field] = value;
            assert!(compile(&serde_json::to_vec(&changed).unwrap())
                .err()
                .unwrap()
                .contains(expected));
        }
        for (reference, expected) in [
            ("https://example.invalid/schema", "only local"),
            ("#/definitions/missing", "unresolved"),
            (
                "#/definitions/goalCheckpointEvidenceBytes",
                "does not descend",
            ),
        ] {
            let mut changed = source.clone();
            changed["definitions"]["goalCheckpointEvidenceBytes"] =
                serde_json::json!({"$ref": reference});
            assert!(compile(&serde_json::to_vec(&changed).unwrap())
                .err()
                .unwrap()
                .contains(expected));
        }
    }

    #[test]
    fn generated_identifiers_refuse_collisions_before_emission() {
        let source: serde_json::Value = serde_json::from_slice(SOURCE).unwrap();
        for names in [
            vec!["record"],
            vec!["Record"],
            vec!["self"],
            vec!["Self"],
            vec!["extra", "Extra"],
        ] {
            let mut changed = source.clone();
            for name in names {
                changed["definitions"][name] = serde_json::json!({});
            }
            assert!(compile(&serde_json::to_vec(&changed).unwrap())
                .err()
                .unwrap()
                .contains("reserved or duplicated"));
        }
        for name in [
            "",
            "_",
            "has__gap",
            "_leading",
            "trailing_",
            "self",
            "UPPER",
        ] {
            let mut changed = source.clone();
            changed["definitions"]["streamEvent"]["oneOf"][0]["properties"]["type"]["const"] =
                serde_json::json!(name);
            assert!(compile(&serde_json::to_vec(&changed).unwrap())
                .err()
                .unwrap()
                .contains("unsupported generated discriminator"));
        }
        let mut reordered = source;
        reordered["oneOf"].as_array_mut().unwrap().reverse();
        let compiled = compile(&serde_json::to_vec(&reordered).unwrap()).unwrap();
        assert_eq!(compiled.discriminators["SystemKind"].len(), 13);
    }
}
